CREATE TABLE PD_2023_01 AS
SELECT * FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK01;

SELECT * FROM PD_2023_01;

--Create a new field 'Bank'

ALTER TABLE PD_2023_01
ADD COLUMN Bank VARCHAR;

--Use Regex to find the Bank intials to populate the new Bank field

UPDATE PD_2023_01
SET Bank = REGEXP_SUBSTR(TRANSACTION_CODE, '[A-Z]*');

--Replace the values for the field 'Online or in Person'

ALTER TABLE PD_2023_01
ADD COLUMN ONLINE_OR_IN_PERSON_vc VARCHAR;

UPDATE PD_2023_01
SET ONLINE_OR_IN_PERSON_vc = 
    CASE
    WHEN ONLINE_OR_IN_PERSON_vc = 1 THEN 'Online'
    WHEN ONLINE_OR_IN_PERSON_vc = 2 THEN 'In Person'
    ELSE ''
    END;

ALTER TABLE PD_2023_01
DROP COLUMN ONLINE_OR_IN_PERSON;

ALTER TABLE PD_2023_01
RENAME COLUMN ONLINE_OR_IN_PERSON_vc to ONLINE_OR_IN_PERSON;

--Find the weekday of Transaction Date

UPDATE PD_2023_01
SET TRANSACTION_DATE = DAYNAME( TO_DATE(TRANSACTION_DATE, 'DD/MM/YYYY HH:MI:SS') );

--Output table 1

SELECT BANK, SUM(VALUE)
FROM PD_2023_01
GROUP BY BANK;

--Output table 2

SELECT BANK, ONLINE_OR_IN_PERSON, TRANSACTION_DATE, SUM(VALUE)
FROM PD_2023_01
GROUP BY BANK, TRANSACTION_DATE, ONLINE_OR_IN_PERSON
ORDER BY BANK, TRANSACTION_DATE;

--Output table 3

SELECT BANK, CUSTOMER_CODE, SUM(VALUE)
FROM PD_2023_01
GROUP BY BANK, CUSTOMER_CODE
ORDER BY BANK;