WITH transactions AS
    (SELECT MONTHNAME(TO_DATE(TRANSACTION_DATE, 'DD/MM/YYYY HH:MI:SS')) TRANSACTION_MONTH
        , REGEXP_SUBSTR(TRANSACTION_CODE, '[A-Z]*') BANK
        , SUM(VALUE) VALUE
        , RANK() OVER(PARTITION BY TRANSACTION_MONTH ORDER BY SUM(VALUE) DESC) BANK_RANK_PER_MONTH
    FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK01
    GROUP BY 1, 2)
    
    ,bank_rankings AS
    (SELECT BANK BANK1
        , AVG(BANK_RANK_PER_MONTH) AVG_RANK_PER_BANK
        FROM transactions
        GROUP BY BANK)
        
    , rank_averages AS
    (SELECT BANK_RANK_PER_MONTH BANK_RANK_PER_MONTH1
        , AVG(VALUE) AVG_TRANSACTION_VALUE_PER_RANK
        FROM transactions
        GROUP BY BANK_RANK_PER_MONTH)
        
SELECT TRANSACTION_MONTH
    , BANK
    , VALUE
    , BANK_RANK_PER_MONTH
    , AVG_RANK_PER_BANK
    , AVG_TRANSACTION_VALUE_PER_RANK
FROM bank_rankings
JOIN transactions ON transactions.BANK = bank_rankings.BANK1
JOIN rank_averages ON transactions.BANK_RANK_PER_MONTH = rank_averages.BANK_RANK_PER_MONTH1
ORDER BY TRANSACTION_MONTH, BANK_RANK_PER_MONTH;