--Input data sources

CREATE TABLE PD_2023_03_TRANSACTIONS AS
SELECT * FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK01;

SELECT * FROM PD_2023_03_TRANSACTIONS;

CREATE TABLE PD_2023_03_TARGETS AS
SELECT * FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK03_TARGETS;

SELECT * FROM PD_2023_03_TARGETS;

--Filter to only relevant data

DROP TABLE PD_2023_03_TRANSACTIONS;

CREATE TABLE PD_2023_03_TRANSACTIONS AS
SELECT * FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK01
WHERE CONTAINS(TRANSACTION_CODE, 'DTB');

SELECT * FROM PD_2023_03_TRANSACTIONS;

--Replace '1' and '2' with 'Online' and 'In Person'

ALTER TABLE PD_2023_03_TRANSACTIONS
ADD COLUMN ONLINE_OR_IN_PERSON_vc VARCHAR;

UPDATE PD_2023_03_TRANSACTIONS
SET ONLINE_OR_IN_PERSON_vc = 
    CASE
    WHEN ONLINE_OR_IN_PERSON = 1 THEN 'Online'
    WHEN ONLINE_OR_IN_PERSON = 2 THEN 'In-Person'
    END
;

ALTER TABLE PD_2023_03_TRANSACTIONS
DROP COLUMN ONLINE_OR_IN_PERSON;

ALTER TABLE PD_2023_03_TRANSACTIONS
RENAME COLUMN ONLINE_OR_IN_PERSON_vc TO ONLINE_OR_IN_PERSON;

--Set date to be Quarter

UPDATE PD_2023_03_TRANSACTIONS
SET TRANSACTION_DATE =
    QUARTER(TO_DATE(TRANSACTION_DATE, 'DD/MM/YYYY HH:MI:SS'));

--Summarise transaction data for each Q and transaction type

CREATE TABLE PD_2023_03_TRANSACTIONS_agg AS
SELECT ONLINE_OR_IN_PERSON, TRANSACTION_DATE, SUM(VALUE) TOTAL_VALUE
FROM PD_2023_03_TRANSACTIONS
GROUP BY TRANSACTION_DATE, ONLINE_OR_IN_PERSON;

SELECT * FROM PD_2023_03_TRANSACTIONS_agg;

--Pivot Target dataset

CREATE TABLE PD_2023_03_TARGETS_pv AS
SELECT * FROM PD_2023_03_TARGETS
UNPIVOT(VALUE FOR QUARTER IN (Q1, Q2, Q3, Q4));

SELECT * FROM PD_2023_03_TARGETS_pv;

--Edit Quarter field to remove 'Q' and change to NUM data type

UPDATE PD_2023_03_TARGETS_pv
SET QUARTER = REPLACE(QUARTER, 'Q', '');

UPDATE PD_2023_03_TARGETS_pv
SET QUARTER = TO_NUMBER(QUARTER);

--Join tables

ALTER TABLE PD_2023_03_TARGETS_PV
RENAME COLUMN ONLINE_OR_IN_PERSON TO TRANSACTION_TYPE;

CREATE TABLE PD_2023_03_COMBINED AS
SELECT *
FROM PD_2023_03_TRANSACTIONS_AGG agg_table
JOIN PD_2023_03_TARGETS_PV piv_table
    ON agg_table.ONLINE_OR_IN_PERSON = piv_table.TRANSACTION_TYPE
    AND agg_table.TRANSACTION_DATE = piv_table.QUARTER;

DROP TABLE PD_2023_03_COMBINED;

SELECT * FROM PD_2023_03_COMBINED;

--Create field to show variance from Target

ALTER TABLE PD_2023_03_COMBINED
ADD COLUMN VARIANCE VARCHAR;

UPDATE PD_2023_03_COMBINED
SET VARIANCE = TOTAL_VALUE - VALUE;

--Create output table

CREATE TABLE PD_2023_03_OUTPUT AS
SELECT TRANSACTION_TYPE, QUARTER, TOTAL_VALUE, VALUE TARGER_VALUE, VARIANCE
FROM PD_2023_03_COMBINED
ORDER BY TRANSACTION_TYPE, QUARTER;

SELECT * FROM PD_2023_03_OUTPUT;