--Input data sources

CREATE TABLE PD_2023_02_SC AS
SELECT * FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK02_SWIFT_CODES;

SELECT * FROM PD_2023_02_SC;

CREATE TABLE PD_2023_02 AS
SELECT * FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK02_TRANSACTIONS;

SELECT * FROM PD_2023_02;

--Remove dashes from Sort Code

UPDATE PD_2023_02
SET SORT_CODE = REPLACE(SORT_CODE, '-', '');

--Bring in additional info from lookup table

ALTER TABLE PD_2023_02
RENAME COLUMN BANK TO BANK_NAME;

CREATE TABLE PD_2023_02_COMBINED AS
(SELECT *
FROM PD_2023_02_SC lookup
INNER JOIN PD_2023_02 main
ON main.BANK_NAME = lookup.BANK);

SELECT * FROM PD_2023_02_COMBINED;

--Add field for Country Code (all UK)

ALTER TABLE PD_2023_02_COMBINED
ADD COLUMN COUNTRY_CODE VARCHAR;

UPDATE PD_2023_02_COMBINED
SET COUNTRY_CODE = 'GB';

--Create IBAN string field

ALTER TABLE PD_2023_02_COMBINED
ADD COLUMN IBAN VARCHAR;

UPDATE PD_2023_02_COMBINED
SET IBAN = CONCAT( TO_VARCHAR(COUNTRY_CODE)
                    , TO_VARCHAR(CHECK_DIGITS)
                    , TO_VARCHAR(SWIFT_CODE)
                    , TO_VARCHAR(SORT_CODE)
                    , TO_VARCHAR(ACCOUNT_NUMBER)
);

--Create Output table
CREATE TABLE PD_2023_02_Output AS
SELECT TRANSACTION_ID, IBAN
FROM PD_2023_02_COMBINED;

SELECT * FROM PD_2023_02_Output;