--Input all data sources and union; include new field to show which month of data this is

CREATE TABLE PD_2023_04 AS
    
    SELECT *, 'Jan' AS DATA_MONTH FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_JANUARY
    UNION ALL
    SELECT *, 'Feb' AS DATA_MONTH FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_FEBRUARY
    UNION ALL
    SELECT *, 'Mar' AS DATA_MONTH FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_MARCH
    UNION ALL
    SELECT *, 'Apr' AS DATA_MONTH FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_APRIL
    UNION ALL
    SELECT *, 'May' AS DATA_MONTH FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_MAY
    UNION ALL
    SELECT *, 'Jun' AS DATA_MONTH FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_JUNE
    UNION ALL
    SELECT *, 'Jul' AS DATA_MONTH FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_JULY
    UNION ALL
    SELECT *, 'Aug' AS DATA_MONTH FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_AUGUST
    UNION ALL
    SELECT *, 'Sep' AS DATA_MONTH FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_SEPTEMBER
    UNION ALL
    SELECT *, 'Oct' AS DATA_MONTH FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_OCTOBER
    UNION ALL
    SELECT *, 'Nov' AS DATA_MONTH FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_NOVEMBER
    UNION ALL
    SELECT *, 'Dec' AS DATA_MONTH FROM TIL_PLAYGROUND.PREPPIN_DATA_INPUTS.PD2023_WK04_DECEMBER;

    SELECT * FROM PD_2023_04;

--Deal with fields that were incorrectly combined during Union step.  USE PIVOT...AS to rename columns without quote marks.

CREATE TABLE PD_2023_04_pv AS 
    SELECT * FROM
    PD_2023_04
    PIVOT (MAX(VALUE) FOR DEMOGRAPHIC IN('Account Type', 'Ethnicity', 'Date of Birth'))
    AS p (ID, JOINING_DAY, DATA_MONTH, ACCOUNT_TYPE, ETHNICITY, DOB);

SELECT * FROM PD_2023_04_pv;

--Create Joining Date field based on info currently in table; assume year is 2023.

ALTER TABLE PD_2023_04_pv
ADD COLUMN JOINING_DATE DATE;

UPDATE PD_2023_04_pv
SET JOINING_DATE = TO_DATE(
    '2023-' || DATA_MONTH || '-' || TO_VARCHAR(JOINING_DAY) 
, 'YYYY-Mon-DD');

--Remove duplicate records, defaulting to earliest available Joining Date for each customer; output table of results

CREATE TABLE PD_2023_04_OUTPUT AS
SELECT ID, MIN(JOINING_DATE) JOINED_DATE, ACCOUNT_TYPE, ETHNICITY, DOB DATE_OF_BIRTH
FROM PD_2023_04_pv
GROUP BY ID, ACCOUNT_TYPE, ETHNICITY, DOB;

SELECT * FROM PD_2023_04_OUTPUT;